#!/usr/bin/env node
/*
 * build-i18n.js
 * ----------------
 * Single source of truth: i18n/*.json
 * Generated artifact:     js/i18n-data.js  (inlines every language so the page
 *                         works from file:// and needs no extra network fetch).
 *
 * Usage:
 *   node build-i18n.js
 *
 * To add a language:
 *   1. Create i18n/<lang>.json (same key tree as en.json).
 *   2. Run `node build-i18n.js` and commit BOTH files.
 * The language dropdown, browser-default detection, and switcher all pick the
 * new language up automatically (see js/app.js) — no HTML or app.js edits needed.
 */
const fs = require('fs');
const path = require('path');

const I18N_DIR = path.join(__dirname, 'i18n');
const OUT_FILE = path.join(__dirname, 'js', 'i18n-data.js');
const DEFAULT_LANG = 'en';

// Discover languages: every *.json in i18n/.
const langs = fs
  .readdirSync(I18N_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.replace(/\.json$/, ''))
  .sort((a, b) => (a === DEFAULT_LANG ? -1 : b === DEFAULT_LANG ? 1 : a.localeCompare(b)));

if (!langs.length) {
  console.error('build-i18n: no language files found in i18n/');
  process.exit(1);
}
if (!langs.includes(DEFAULT_LANG)) {
  console.error(`build-i18n: default language "${DEFAULT_LANG}.json" missing`);
  process.exit(1);
}

// Validate structural consistency against the default language (strict, future-proof).
function collectKeys(node, prefix = '') {
  return Object.entries(node).flatMap(([k, v]) =>
    typeof v === 'object' && v !== null
      ? collectKeys(v, prefix + k + '.')
      : [prefix + k]
  );
}
const defaultKeys = new Set(collectKeys(JSON.parse(fs.readFileSync(path.join(I18N_DIR, `${DEFAULT_LANG}.json`), 'utf8'))));
const problems = [];
for (const lang of langs) {
  if (lang === DEFAULT_LANG) continue;
  const data = JSON.parse(fs.readFileSync(path.join(I18N_DIR, `${lang}.json`), 'utf8'));
  const keys = new Set(collectKeys(data));
  for (const k of defaultKeys) if (!keys.has(k)) problems.push(`${lang}.json: missing key "${k}"`);
  for (const k of keys) if (!defaultKeys.has(k)) problems.push(`${lang}.json: extra key "${k}" (not in en)`);
}
if (problems.length) {
  console.error('build-i18n: language files are not strictly consistent:');
  problems.forEach((p) => console.error('  - ' + p));
  process.exit(1);
}

// Emit js/i18n-data.js.
const banner = [
  '/* AUTO-GENERATED by build-i18n.js — do not edit by hand. */',
  '/* Source of truth: i18n/*.json. Regenerate with: node build-i18n.js */',
  '',
  'window.i18nData = window.i18nData || {};',
  '',
].join('\n');

const body = langs
  .map((lang) => {
    const data = JSON.parse(fs.readFileSync(path.join(I18N_DIR, `${lang}.json`), 'utf8'));
    return `window.i18nData.${lang} = ${JSON.stringify(data, null, 2)};`;
  })
  .join('\n\n');

fs.writeFileSync(OUT_FILE, banner + body + '\n');
console.log(`build-i18n: wrote ${path.relative(process.cwd(), OUT_FILE)} with languages: ${langs.join(', ')}`);
